POST http://localhost:3000/login
Content-Type: application/json

{
"username": "joe", 
"password": "password",
"email": "example@email.com"

}

###

POST http://localhost:3000/login
Content-Type: application/json

{
"password": "3",
"email": "3@3"

}