GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
"username": "Tom", 
"password": "password",
"email": "example@email.com"

}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
"username": "Tom", 
"password": "password",
"email": "example@email.com"

}

###

DELETE http://localhost:3000/users/6623d3ae308544236752487b