GET http://localhost:3000/reviews

###

GET http://localhost:3000/reviews/662295cf091caaae801eeee8

###

POST http://localhost:3000/reviews/new
Content-Type: application/json

{
    "userID":"66244e469e5c10e0d34cb9e3",
    "title": "That Place sucked",
    "address": "24 Kings Avenue",
    "coordinate": "51.0527598,-1.3274846",
    "reviewBody": "property managments bad",
    "stars": "2"
}

###

POST http://localhost:3000/reviews/new
Content-Type: application/json

{
    "userID":"66244e469e5c10e0d34cb9e3",
    "title": "Not bad",
    "address": "71 Stanmore Lane, Winchester",
    "coordinate": "51.052541,-1.3324821",
    "reviewBody": "nice view",
    "stars": "4"
}

###

DELETE http://localhost:3000/reviews/662295cf091caaae801eeee8

###

PATCH http://localhost:3000/reviews/update/664b76ac4ab530a68e2df596
Content-Type: application/json

{
    "title": "That Place wasnt brill",
    "reviewBody": "test",
    "stars": "3",
    "address": "21 kings avenue, winchester"
}