GET http://localhost:3000/reviews

###

GET http://localhost:3000/reviews/662295cf091caaae801eeee8

###

POST http://localhost:3000/reviews
Content-Type: application/json

{
    "title": "That Place sucked",
    "location": "24 Kings",
    "review": "property managments shit",
    "stars": "6"
}

###

DELETE http://localhost:3000/reviews/662295cf091caaae801eeee8

###

PATCH http://localhost:3000/reviews/662678f6b698d598866773f8
Content-Type: application/json

{
    "title": "That Place sucked balls"
}